# apiVersion: v1
# kind: Service
# metadata:
#   name: backend-service
#   namespace: shop
# spec:
#   selector:
#     app: order-api
#   ports:
#     - port: 8000
#       targetPort: 8000
#       protocol: TCP
#   type: ClusterIP

apiVersion: v1
kind: Service

metadata:
  name: backend-service
  namespace: shopsphere

spec:

  selector:
    app: backend

  ports:

    - port: 8000
      targetPort: 8000

  type: ClusterIP