# apiVersion: v1
# kind: Secret
# metadata:
#   name: shop-secret
#   namespace: shop
# type: Opaque
# stringData:
#   POSTGRES_DB: shopshere
#   POSTGRES_USER: shopshere_app
#   POSTGRES_PASSWORD: sam123


apiVersion: v1
kind: Secret

metadata:
  name: shopsphere-secret
  namespace: shopsphere

type: Opaque

stringData:

  DB_USER: shopsphere

  DB_PASSWORD: shopsphere123