# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: pg-deploy
#   namespace: shop
# spec:
#   replicas: 3
#   selector:
#     matchLabels:
#       app: shop-app
#   template:
#     metadata:
#       labels:
#         app: shop-app
#     spec:
#       containers:
#         - name: postrgres
#           image: postgres:16
#           ports:
#             - containerPort: 5432
#           resources:
#             requests:
#               cpu: 100m
#               memory: 256Mi
#             limits:
#               cpu: 500m
#               memory: 512Mi
#           volumeMounts:
#             - name: shop-mount
#               mountPath: /var/lib/postgresql/data
#           env:
#             - name: POSTGRES_DB
#               valueFrom:
#                 secretKeyRef:
#                   name: shop-secret
#                   key: POSTGRES_DB
#             - name: POSTGRES_USER
#               valueFrom:
#                 secretKeyRef:
#                   name: shop-secret
#                   key: POSTGRES_USER
#             - name: POSTGRES_PASSWORD
#               valueFrom:
#                 secretKeyRef:
#                   name: shop-secret
#                   key: POSTGRES_PASSWORD
#           # readinessProbe:
#           #   exec:
#           #     command:
#           #       - sh
#           #       - -c
#           #       - pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
#           #   initialDelaySeconds: 10
#           #   periodSeconds: 5
#           # livenessProbe:
#           #   exec:
#           #     command:
#           #       - sh
#           #       - -c
#           #       - pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
#           #   initialDelaySeconds: 30
#           #   periodSeconds: 10
#           livenessProbe:
#             exec:
#               command:
#               - sh
#               - -c
#               - pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
#             initialDelaySeconds: 60   # Increased from 30s
#             periodSeconds: 10
#             failureThreshold: 6       # Gives extra safety buffer
#           readinessProbe:
#             exec:
#               command:
#               - sh
#               - -c
#               - pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
#             initialDelaySeconds: 30   # Increased from 10s
#             periodSeconds: 10         # Increased from 5s
#             failureThreshold: 6

#       volumes:
#         - name: shop-mount
#           persistentVolumeClaim:
#             claimName: shop-pvc



apiVersion: apps/v1
kind: Deployment

metadata:
  name: postgres
  namespace: shopsphere

spec:

  replicas: 1

  selector:
    matchLabels:
      app: postgres

  template:

    metadata:
      labels:
        app: postgres

    spec:

      containers:

        - name: postgres

          image: postgres:16-alpine

          ports:
            - containerPort: 5432

          env:

            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: shopsphere-config
                  key: DB_NAME

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: shopsphere-secret
                  key: DB_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shopsphere-secret
                  key: DB_PASSWORD

          volumeMounts:

            - name: postgres-storage
              mountPath: /var/lib/postgresql/data

          readinessProbe:

            exec:
              command:
                - sh
                - -c
                - pg_isready -U "$POSTGRES_USER"

            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:

            exec:
              command:
                - sh
                - -c
                - pg_isready -U "$POSTGRES_USER"

            initialDelaySeconds: 30
            periodSeconds: 10

      volumes:

        - name: postgres-storage

          persistentVolumeClaim:
            claimName: postgres-pvc